### ISSUE TITLE
SyntaxError: invalid character '［' (U+FF3B)

### ISSUE THREAD

**Issue by aijuncheng** [AIFSH/CosyVoice-ComfyUI#43]
Traceback (most recent call last):
  File "E:\stableDiffusion\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stableDiffusion\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\__init__.py", line 1, in <module>
    from .nodes import TextNode, CosyVoiceNode, LoadSRT, CosyVoiceDubbingNode
  File "E:\stableDiffusion\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 170
    output_list = ［］
                  ^
SyntaxError: invalid character '［' (U+FF3B)

**Comment by Seaual** [comment]
![image](https://github.com/user-attachments/assets/e7c2d799-e9ce-4008-a3a7-2552472e03d0)
修改为英文字符就行了

**Comment by AIFSH** [comment]
手机上改的代码，再试试

**Comment by leegang** [comment]
> 手机上改的代码，再试试

有新的 bug，size 不对

**Comment by Pythonpa** [comment]
stack expects each tensor to be equal size, but got [1, 123189] at entry 0 and [1, 78203] at entry 1 is:issue

**Comment by leegang** [comment]
stack expects each tensor to be equal size, but got [1, 123189] at entry 0 and [1, 78203] at entry 1 is:issue

**Comment by leegang** [comment]
How was it fixed?

At 2024-09-10 13:48:50, "AI_master_workflow" ***@***.***> wrote:

stack expects each tensor to be equal size, but got [1, 123189] at entry 0 and [1, 78203] at entry 1 is:issue

**Comment by leegang** [comment]
Fixed   @48
