### ISSUE TITLE
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer

### ISSUE THREAD

**Issue by konradre** [AIFSH/CosyVoice-ComfyUI#52]
```
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 140, in generate
    self.cosyvoice = CosyVoice(model_dir)
  File "D:\ComfyUI\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\cosyvoice.py", line 30, in __init__
    configs = load_hyperpyyaml(f)
  File "D:\ComfyUI\venv\lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "D:\ComfyUI\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\ComfyUI\venv\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\ComfyUI\venv\lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer
```

**Comment by royaiagent** [comment]
我的 cosyvoice 前几天还能正常用，昨天开始也是遇到这个问题；另外就是报错:  Files，两个错误来回交替

**Comment by royaiagent** [comment]
!!! Exception during processing!!! 'Files'
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/CosyVoice-ComfyUI/nodes.py", line 125, in generate
    snapshot_download(model_id="iic/CosyVoice-300M-Instruct",local_dir=model_dir)
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 84, in snapshot_download
    return _snapshot_download(
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 235, in _snapshot_download
    repo_files = _api.get_model_files(
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/hub/api.py", line 657, in get_model_files
    for file in d[API_RESPONSE_FIELD_DATA]['Files']:
KeyError: 'Files'

**Comment by royaiagent** [comment]
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/c3dc4689-06d7-4fef-a9c1-b31c897718c1">

@leegang Can you help me with this ‘Files’ problem?

**Comment by wanghkkk** [comment]
yes,the same error,how can i fix this?

**Comment by ammahmoudi** [comment]
same:
Downloading Model to directory: C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI\pretrained_models\CosyVoice-300M-SFT
input frame rate=50
!!! Exception during processing !!! There is no such entity as whisper.tokenizer.get_tokenizer
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 141, in generate
    self.cosyvoice = CosyVoice(model_dir)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\cosyvoice.py", line 30, in __init__
    configs = load_hyperpyyaml(f)
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer

**Comment by thinkluck** [comment]
我也遇到了
