### ISSUE TITLE
错误提示依然指出，虽然你在虚拟环境中成功安装了 librosa，但 ComfyUI 运行时未能找到这个库。这可能是因为 ComfyUI 运行时没有使用你的虚拟环境 myenv。

### ISSUE THREAD

**Issue by linwankeji** [AIFSH/CosyVoice-ComfyUI#57]
Traceback (most recent call last):
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI\__init__.py", line 1, in <module>
    from .nodes import TextNode, CosyVoiceNode, LoadSRT, CosyVoiceDubbingNode
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 3, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

Cannot import E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\CosyVoice-ComfyUI module for custom nodes: No module named 'librosa'

**Comment by SpenserCai** [comment]
如果你是手动安装的，你需要切换到comfyui的venv然后在执行pip安装，同时启动comfyui时也要在venv中
